imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
format_macro_matchers = true
group_imports = "StdExternalCrate"
reorder_impl_items = true
use_field_init_shorthand = true
unstable_features = true
style_edition = "2024"
